<section class ="contact__wrapper">
        <h1>Contactez nous !</h1>
        <form method ="POST">
            <div class ="form__double__input__wrapper">
                <div class ="form__input__wrapper">
                    <label class ="form__label" for="login">Votre email</label>
                    <input class ="form__input" id = "login" type="email" name="email" required autocomplete ="email">
                </div>
            </div>
            <div class ="form__double__input__wrapper">
                <div class ="form__input__wrapper">
                    <label class ="form__label" for="message">Votre message</label>
                    <textarea class = "form__input" id="message" name= "message" maxlength="300"></textarea>
                </div>
            </div>
            <button type="submit" name="contact">
                Envoyer
            </button>
        </form>
    </section>