<header>
    <div class ="mobile__header__wrapper">
        <a title ="Accueil" href ="index.php?page=home" class ="homeLink" >
            We love f
            <img class ="plateLogo" src="./medias/images/logo/plateLogo.jpg">
            <img class ="plateLogo" src="./medias/images/logo/plateLogo.jpg">
            d
        </a>
        <i class="fa-solid fa-bars"></i>
    </div>
    <nav>
        <ul>
            <li>connexion / inscription</li>
            <li>Ajouter une recette</li>
            <li>Contact</li>
            <li>Se déconnecter</li>
        </ul>
    </nav>
</header>