<div class ="burgerNav__wrapper">
    <ul class ="burgerNav__list">
        <li class ="burgerNav__list__item">
            <div>
                <i class="fa-solid fa-archway burgerNav__list__item__icon"></i>
            </div>
            <a title ="page d'accueil" class ="burgerNav__list__item__link" href ="index.php?page=home">Accueil</a>
        </li>
        <li class ="burgerNav__list__item">
            <div>
                <i class="fa-solid fa-user-tie burgerNav__list__item__icon"></i>
            </div>
            <a title ="connexion / inscription" class ="burgerNav__list__item__link" href ="index.php?page=log">Connexion / Inscription</a>
        </li>
        <li class ="burgerNav__list__item">
            <div>
                <i class="fa-solid fa-feather burgerNav__list__item__icon"></i>
            </div>
            <a title ="ajout recette" class ="burgerNav__list__item__link" href ="index.php?page=add-recipe">Ajouter une recette</a>
        </li>
        <li class ="burgerNav__list__item">
            <div>
                <i class="fa-solid fa-envelope burgerNav__list__item__icon"></i>
            </div>
            <a title ="contact" class ="burgerNav__list__item__link" href ="index.php?page=contact">Contact</a>
        </li>
        <li class ="burgerNav__list__item">
            <div>
                <i class="fa-solid fa-power-off burgerNav__list__item__icon"></i>
            </div>
            <a title ="contact" class ="burgerNav__list__item__link" href ="index.php?page=disconnect">Se déconnecter</a>
        </li>
    </ul>
</div>